MyFlask:
  # component: '@serverless/tencent-flask'
  component: ../
  inputs:
    region: ap-guangzhou
    functionName: flask-function
    namespace: test
    code: ./
    functionConf:
      timeout: 10
      memorySize: 128
      environment:
        variables:
          TEST: vale
      vpcConfig:
        subnetId: ''
        vpcId: ''
    apigatewayConf:
      protocols:
        - https
      environment: release
